### ISSUE TITLE
Initializing Cog makes it impossible to click or focus UMG buttons even though input is disabled

### ISSUE THREAD

**Issue by erdemserhatergen** [arnaud-jamin/Cog#12]
Title says most of it but here is extra information. I have umg buttons on my canvas, they are marked as IsFocusable and I also tried to set input mode to game and UI after disabling Cog input. Even though I close all windows of Cog and disable input, I still see CogImgui canvas covering whole viewport and widget reflector can't even pickup my umg widgets.

For now I shutdown Cog window manager to get focus back to umg widgets and that solves the problem. Is there another way to solve this issue without shutting down Cog? I'm not sure if it solves the problem but maybe Imgui module can have shared input mode like segross imgui implementation to share input with game without fully consuming it.

**Comment by arnaud-jamin** [comment]
I will put the task of implementing shared input on top of my list. Shouldn't be too long for the first version. I'm not sure if it is going to be enough to support CommonUI. 
I'll try to pout CommonUI in the sample as a secondary task.

**Comment by arnaud-jamin** [comment]
https://github.com/arnaud-jamin/Cog/commit/294cb566106de52f1c73425a2db0559840f0cf93 should fix the UI not receiving input when imgui input is disabled.

Note that using the function "SetInputModeUIOnly" doesn't interact well with Cog, because it prevent the Cog key binding to be executed. I think a better way nowadays is to use the Enhanced input mapping (like in the sample)

I still need to add shared input.

**Comment by erdemserhatergen** [comment]
Wow this was really quick fix. Thank you. I'll try and see if it fixes my issue today and report the results of same test.

Shared input is great thing but not mandatory since you can toggle.

**Comment by erdemserhatergen** [comment]
Yes

> [294cb56](https://github.com/arnaud-jamin/Cog/commit/294cb566106de52f1c73425a2db0559840f0cf93) should fix the UI not receiving input when imgui input is disabled.
> 
> Note that using the function "SetInputModeUIOnly" doesn't interact well with Cog, because it prevent the Cog key binding to be executed. I think a better way nowadays is to use the Enhanced input mapping (like in the sample)
> 
> I still need to add shared input.

Yes this commit fixes the issue. Thank you a lot. I'm closing the issue now.
