### ISSUE TITLE
Multiplayer support

### ISSUE THREAD

**Issue by Skylonxe** [arnaud-jamin/Cog#19]
Hello, 

there seem to an issue that unlike Gameplay Debugger, Cog is using local data even for functionalities which are available only on the server.

As an example, CogAIWindow_Blackboard takes local AIController what makes it unusable in multiplayer environment as AIController and Blackboard exist only on the server. Similar for other windows like CogAbilityWindow_Tags where GameplayDebugger distinguishes between server-side state and client-side states.

Additionally, I find it more challenging to write replicated debugging than when using gameplay debugger. Because of that I am not yet pushing on using it as gameplay debugger category is often easier to write. The nice thing about something like FGameplayDebuggerCategory (e.g. FGameplayDebuggerCategory_Abilities) is that all you need to do is to override two functions. One to collect data on the server and a different one to display data on the client. This simplifies things a lot as you just fill structure and then draw the data from the structure on the other end. No need for custom replicator actors. It would be awesome if Cog supported similar simple way of networked debugging, possibly by offering something like FGameplayDebuggerCategory::CollectData() in UCogWindow. As a bonus, if the UCogWindows were replicated, it would be also possible to do RPCs directly within them, so button presses could be easily implemented too.

Cog is on the good way to become a cool replacement for gameplay debugger, thanks and keep up the good work!

**Comment by HoussineMehnik** [comment]
NetImgui works well in my case , I'm able to debug on ListenServer.
All I did is creating "CogImguiContext_NoViewport" same as CogImguiContext but without Slate and input stuff.
For now I'm using a simple define "USE_VIEWPORT_IMGUI_CONTEXT" to switch which context.

But I think having something like :
- FCogImguiContextBase -> FCogImguiContext, FCogNetImguiContext, ...) 
- CogWindowManager->InitConext<ContextClass>()
should be a better solution

**Comment by Skylonxe** [comment]
Interesting, I hadn't heard of NetImGui before, so thanks for sharing!

Having the debugging on a separate screen and window could definitely be useful. It could also pave the way for Dear ImGui admin tools on dedicated servers. This might be easier to work with than the Gameplay Debugger, as it wouldn't require dealing with replication, and I assume it wouldn't be affected by issues related to Unreal Engine's network performance or update rate.

There should still be a way to do client-side only debug drawing, possibly even allowing the Unreal Engine application to act as a NetImGui server, enabling it to draw directly in the same window. Figuring out how to do something like the Gameplay Debugger's 3D debug drawing could be tricky tho.

**Comment by arnaud-jamin** [comment]
Regarding the display of server 3D debug drawing on the client, Cog handles some of that  in a similar way as the gameplay debugger. 

Almost all the debug draw functions of Cog in FCogDebugDraw replicates from the server to the client. See FCogDebugDraw::Sphere for example.

Cog uses log categories to debug. 
You can activate a log category of the server from the client using the log category window.

See this part of the video:
https://youtube.com/clip/Ugkx7xPz3Sf-F-jhRhoonwN8ToJrM_w-lX6D?si=ZTlziScyVfCfQcn4

**Comment by arnaud-jamin** [comment]
NetImgui is supported with 9a0c32c
