### ISSUE TITLE
SetToggleInputKey does not work.

### ISSUE THREAD

**Issue by ThaiNhatMinh** [arnaud-jamin/Cog#2]
I use API same as demo

> FCogImguiModule::Get().SetToggleInputKey(FCogImGuiKeyInfo(EKeys::RightAlt));

But only the default `Tab` key is work.

**Comment by arnaud-jamin** [comment]
The sample doesn't use this anymore, instead the toggle key can be configured from the Window/Settings window:
![image](https://github.com/arnaud-jamin/Cog/assets/13844285/cea5dc8f-10c4-407a-9c18-fca1bccc28f3)

**Comment by ThaiNhatMinh** [comment]
I use `Window/Settings` but it got reset every time I launch.

**Comment by arnaud-jamin** [comment]
I've changed the way shortcuts are handled.
There is now a new Command Bindings window:

![image](https://github.com/arnaud-jamin/Cog/assets/13844285/e4819c48-69e7-4f39-a0b6-be9757c8e1cc)
