### ISSUE TITLE
Setup from readme is insufficient to use Cog

### ISSUE THREAD

**Issue by Vaei** [arnaud-jamin/Cog#26]
After following the Setup guide in Readme I can't use F1 or `Cog.ToggleInput` (this command doesn't exist, only `Cog.ToggleSelectionMode` exists, which crashes the editor likely due to the incomplete setup) and nothing in the Readme explains why its missing. It simply doesn't work and there is no context - there are no warnings or errors in the output log, no ensure failing, etc.

I triple checked the steps in the readme to no avail.

So I looked through the example project but I can't find anything related to the setup because there is way too much stuff there - it would be all but impossible to *not* miss whatever it is I need to do with the amount of content.

Could you let me know what is missing and add it to the Readme?

**Comment by arnaud-jamin** [comment]
Can you show your code where you create the UCogWindowManager ? Where you
add Windows, where you Tick it ?

The console comnmands gets created in :
void UCogWindowManager::InitializeInternal()

**Comment by Vaei** [comment]
Ah-hah, so it turns out GameStateBase has tick disabled by default, and the InitializeInternal() stems from the Tick.

In that case, it may be worth simply adding to the Readme a reminder to enable tick on the game state if you do use it :)

**Comment by arnaud-jamin** [comment]
I updated the readme. Thanks!
