### ISSUE TITLE
UE 5.4.4 CogImguiWidget - Context Main Widget becomes invalid at level change?

### ISSUE THREAD

**Issue by JailbreakPapa** [arnaud-jamin/Cog#41]
After Loading into a new level, and pressing F1 to trigger Cog, it expects at CogImguiWidget.
![ExceptionImage](https://github.com/user-attachments/assets/f14b1e52-d22a-42c4-9837-9a5d5257f9d9)

Exception thrown: read access violation.
this->Context->MainWidget.SharedReferenceCount.**ReferenceController** was 0xFFFFFFFFFFFFFFF7.

**Comment by JailbreakPapa** [comment]
This happens on Windows, PS5 and Xbox One and Series Consoles

**Comment by JailbreakPapa** [comment]
@arnaud-jamin

**Comment by JailbreakPapa** [comment]
> also experiencing this on windows. seems that `InputCatcherWidget` never gets removed properly.
> 
> @JailbreakPapa are you calling `CogWindowManager->Shutdown();` at all aswell?

@QUANDINI-byte Yep.

**Comment by QUANDINI-byte** [comment]
> > also experiencing this on windows. seems that `InputCatcherWidget` never gets removed properly.
> > @JailbreakPapa are you calling `CogWindowManager->Shutdown();` at all aswell?
> 
> @QUANDINI-byte Yep.

found a solution, at least that has worked for me :)

in the FCogImguiContext::Shutdown() function definition, look for line 124: 
`GameViewport->RemoveViewportWidgetContent(MainWidget.ToSharedRef());` 
after it place 
`GameViewport->RemoveViewportWidgetContent(InputCatcherWidget.ToSharedRef());`

has worked for the past few days for me, hopefully, it does for you too.

**Comment by arnaud-jamin** [comment]
Fixed in 19d8855
