### ISSUE TITLE
Separate Plugin with sample

### ISSUE THREAD

**Issue by ThaiNhatMinh** [arnaud-jamin/Cog#5]
It is great if the Plugin is separated from the sample. So that I can clone plugin direct to project's Plugin directory and pull source code when necessary.

**Comment by ThaiNhatMinh** [comment]
Sparse checkout is not normal work flow I usually see in open source UE plugin, this is just suggestion.

**Comment by arnaud-jamin** [comment]
Could you point me to an open source plugin that has a sample ?
Thanks!

**Comment by nado** [comment]
> Could you point me to an unreal open source plugin that has a sample ? Thanks!

You can check TemaranWidgets on marketplace (it’s not on github but it’s free), they provide a sample by having it reside in the Content directory of the plugin.
I’d also rather avoid relying on sparse checkout with git.
