### ISSUE TITLE
Cog does not compile in NonUnity mode

### ISSUE THREAD

**Issue by Skylonxe** [arnaud-jamin/Cog#9]
Adding bUseUnity=false; to all *.Build.cs files will show all the missing includes on compilation.

**Comment by arnaud-jamin** [comment]
It should be fixed it with https://github.com/arnaud-jamin/Cog/commit/9a1fe2a3481257d68591abe882299ba8140197af

Do you know if there is a way to set the build to no unity without changing all the Build.cs ?

Thanks for the issue!

**Comment by Skylonxe** [comment]
Thanks a lot & big thanks for Cog! If you are using launcher engine, you can put it in the Target.cs. You can not do it with source distribution because it will compile also engine as non-unity. Another way should be passing -StrictIncludes if you let UAT build just the plugin (Exampe: https://forums.unrealengine.com/t/unreal-build-tool-for-plugin-different-results-local-vs-marketplcae/488493 ).
